<?php

/**
 * The time to wait before manipulating Brightcove API objects.
 *
 * Based on testing 5-6 minutes is the longest lag time.
 */
define('BRIGHTCOVE_RECORDER_API_WAIT', 60 * 6); // 6 mins

/**
 * @file
 * Brightcove recorder module.
 */

module_load_include('inc', 'video_recorder');

/**
 * Implements hook_menu().
 */
function brightcove_recorder_menu() {
  $items = array();
  $items['brightcove_recorder/upload/%'] = array(
    'title' => 'Process recorded video',
    'description' => 'Copy recorded video from flash server to brightcove.',
    'page callback' => 'brightcove_recorder_upload',
    'page arguments' => array(2),
    'access arguments' => array('record video'),
    'type' => MENU_CALLBACK,
  );

  $items['brightcove_recorder/delete/%/%'] = array(
    'title' => 'Request deletion of a recorded video',
    'description' => 'Request deletion of a recorded video from the brightcove server.',
    'page callback' => 'brightcove_recorder_request_delete',
    'page arguments' => array(2, 3),
    'access arguments' => array('record video'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function brightcove_recorder_init() {
  drupal_add_js(drupal_get_path('module', 'brightcove_recorder') . '/brightcove_recorder.js');
}

/**
 * Implements hook_cron().
 */
function brightcove_recorder_cron() {
  $queued_before = time() - BRIGHTCOVE_RECORDER_API_WAIT;
  $result = db_query('SELECT * FROM {brightcove_recorder_queue} WHERE queued < %d', $queued_before);
  while ($row = db_fetch_array($result)) {
    brightcove_recorder_process_item($row);
  }
}

/**
 * Implements hook_field_settings_alter().
 */
function brightcove_recorder_field_settings_alter(&$data, $op, $field) {
  if ('brightcove_video' !== $field['type']) {
    return;
  }

  switch ($op) {
    case 'form':
      $data['title_template'] = array(
        '#type' => 'textfield',
        '#title' => t('Video Title'),
        '#default_value' => !empty($field['title_template']) ? $field['title_template'] : '[title-raw]',
        '#description' => t('Enter the tokens to be used for the title of the submitted video, '
          . 'you can use any <a href="http://drupal.org/node/390482#token-node-group" target="_blank">node tokens</a>.'),
        '#required' => TRUE,
      );
      break;

    case 'save':
      $data[] = 'title_template';
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function brightcove_recorder_form_alter(&$form, &$form_state, $form_id) {

  if (!isset($form['#node']) || !isset($form['type']['#value']) 
    || $form_id != $form['type']['#value'] .'_node_form'
    || !user_access('record video')
    || empty($form['#field_info'])) {
    return;
  }

  foreach ($form['#field_info'] as $name => $field) {
    if ($field['type'] != 'brightcove_video') {
      continue;
    }

    if (!isset($form['#submit'])) {
      $form['#submit'] = array();
    }

    $form['#submit'][] = 'brightcove_recorder_node_form_submit';

    if (!isset($form['#after_build'])) {
      $form['#after_build'] = array();
    }
 
    $form['#after_build'][] = 'brightcove_recorder_node_form_after_build';
    // we only call after_build once regardless of how many brightcove fields in form
    return;
  }
}

function brightcove_recorder_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ('insert' != $op && 'update' != $op) {
    return;
  }

  $fields = _brightcove_recorder_retitle_hack();
  foreach ($fields as $key => $tpl) {
    list($field, $delta) = explode('|', $key);
    if (!empty($node->{$field}[$delta]['video_id'])) {
      $id = $node->{$field}[$delta]['video_id'];
      $title = token_replace($tpl, 'node', $node);
      if (0 <> $delta) {
        $title .= "-{$delta}";
      }
      brightcove_recorder_queue_action($id, 'title', $title);
    }
  }
}

/**
 * Implements form submit callback.
 */
function brightcove_recorder_node_form_submit($form, &$form_state) {
  static $token_enabled;
  if (!isset($token_enabled)) {
    $token_enabled = module_exists('token');
  }

  foreach ($form['#field_info'] as $name => $field) {
    if ($field['type'] != 'brightcove_video') {
      continue;
    }

    $tpl = '[title-raw]';
    if ($token_enabled && !empty($field['title_template'])) {
      $tpl = $field['title_template'];
    }

    $count = $field['multiple'];
    if ($count <= 1) {
      ++$count;
    }

    for ($i = 0; $i < $count; ++$i) {
      if (!empty($form_state['values'][$field['field_name']][$i]['video_id'])) {
        $id = $form_state['values'][$field['field_name']][$i]['video_id'];
        $title = "{$form_state['values']['title']}";
        if ($token_enabled) {
          $key = "{$name}|{$i}";
          _brightcove_recorder_retitle_hack($key, $tpl);
        }
        else {
          if (0 <> $i) {
            $title .= "-{$i}";
          }
          brightcove_recorder_queue_action($id, 'title', $title);
        }
      }
    }
  }
}

/**
 * Works around a limitation of Drupal when creating / updating nodes.
 *
 * The static $list variable store a list of relevant videos to retitle.
 */
function _brightcove_recorder_retitle_hack($key = NULL, $token = NULL) {
  static $list = array();
  if (is_null($key) && is_null($token)) {
    return $list;
  }
  $list[$key] = $token;
}

/**
 * Implements form after_build callback.
 */
function brightcove_recorder_node_form_after_build($form, &$form_state) {

  $record = t('Record');
  $rerecord = t('Rerecord');
  $preset = variable_get('video_recorder_thumbnail_preset', VIDEO_RECORDER_DEFAULT_THUMBNAIL_PRESET);
  $url = imagecache_create_url($preset, variable_get('brightcove_default_thumbnail', brightcove_get_default_image()));
  $img = theme_image($url, t('Thumbnail'), '', array(), FALSE);

  foreach ($form['#field_info'] as $name => $field) {
    if ($field['type'] != 'brightcove_video') {
      continue;
    }

    $field_name = str_replace('_', '-', $field['field_name']);

    $count = $field['multiple'];
    if ($count <= 1) {
      ++$count;
    }

    for ($i = 0; $i < $count; ++$i) {
      $label = $record;
      $thumb = '';
      if (!empty($form_state['values'][$field['field_name']][$i])) {
        $id = brightcove_parse_id($form_state['values'][$field['field_name']][$i]['video_id']);
        if (!is_null($id)) {
          $label = $rerecord;
          $thumb = $img;
        }
      }

      $video_id = video_recorder_id_generate();

      $button = array(
        'record' => array(
          '#type' => 'brightcove_cck_browse_button',
          '#value' => $label,
          '#id' => check_plain("edit-{$field_name}-{$i}-record-{$video_id}"),
          '#attributes' => array('class' => 'brightcove-recorder-record-button'),
          '#tree' => TRUE,
        ),
      );
      if (!empty($form[$name][$i]['actions'])) {
        array_splice($form[$name][$i]['actions'], 1, 0, $button);
      }
      else {
        $form[$name][$i]['actions'] = $button;
      }
      $form[$name][$i]['video_id']['#attributes']['class'] .= " brightcove-video-{$video_id}";

      $thumbnail = array(
        'thumbnail' => array(
          '#value' => '<span id="brightcove-recorder-thumbnail-' . $video_id . '" class="recorder-thumbail">' . $thumb . '</span>',
        ),
      );
      $form[$name][$i]['actions'][] = $thumbnail;
    }
  }
  return $form;
}

/**
 * Handles transfering video from flash server to brightcove.
 */
function brightcove_recorder_upload($video_id) {
  global $user;

  if (!video_recorder_id_verify($video_id)) {
    drupal_set_header('Status: 404 Not Found');
    return drupal_json(array('error' => 'Invalid video ID.'));
  }

  $video_url = video_recorder_playback_http_url($video_id);

  $video_stream = file_get_contents($video_url);
  if (FALSE === $video_stream) {
    drupal_set_header('Status: 500 Internal Server Error');
    return drupal_json(array('error' => 'Failed to download video from flash server.'));
  }

  // hack to create a secure temp file name with .flv exension
  $tmp_file = tempnam(file_directory_temp(), 'video-');
  unlink($tmp_file);
  $tmp_file .= '.flv';
  
  $bytes = file_put_contents($tmp_file, $video_stream);

  if (FALSE === $bytes) {
    @unlink($tmp_file); // we use @ in case permission prevent deleting the temp file
    drupal_set_header('Status: 500 Internal Server Error');
    return drupal_json(array('error' => 'Failed to write video local file.'));
  }

  $meta = array(
    'name' => $video_id,
    'shortDescription' => t('Uploaded video'),
  );

  module_load_include('module', 'brightcove');
  $id = brightcove_upload_video($tmp_file, $meta);
  unlink($tmp_file); // clean up after ourselves
  if (!$id) {
    drupal_set_header('Status: 500 Internal Server Error');
    return drupal_json(array('error' => 'Failed to upload video to brightcove.'));
  }

  // Work around for brightcove API lag for uploads
  $video = new stdClass();
  $video->id = $id;
  $video->name = $video_id;
  brightcove_video_cache_set($id, $video);

  brightcove_recorder_queue_action($id, 'thumb', $video_id);

  return drupal_json(array('brightcove_id' => $id));
}

/**
 * Queue a request to delete a video from the brightcove CDN.
 *
 * @param
 *   $id The Brightcove CDN id for the video.
 * @param
 *   $hash The Brightcove recorder unique video hash.
 */
function brightcove_recorder_request_delete($id, $hash) {
  if (!video_recorder_id_verify($hash)
    || is_null(brightcove_video_cache_get($id))) {
    drupal_set_header('Status: 404 Not Found');
    return drupal_json(array('error' => 'Invalid video'));
  }

  // unset the brightcove video id so it is no longer available
  brightcove_video_cache_set($video_id, NULL);
  brightcove_recorder_queue_action($id, 'delete');
  return drupal_json(array('queued', TRUE));
}

/**
 * Add an item to the delayed processing queue.
 *
 * We do this to get around the limitations of the Brightcove API.
 */
function brightcove_recorder_queue_action($video_id, $action, $data = '') {
  $args = (object) array(
    'brightcove_id' => $video_id,
    'action' => $action,
    'queued' => time());

  if ($data) {
    $args->data = $data;
  }
  drupal_write_record('brightcove_recorder_queue', $args);
}

/**
 * Process a queued item.
 */
function brightcove_recorder_process_item($item) {
  switch ($item['action']) {
    case 'delete':
      if (!brightcove_recorder_delete_video($item['brightcove_id'])) {
        return FALSE;
      }
      break;

    case 'thumb':
      if (!brightcove_recorder_upload_thumb($item['brightcove_id'], $item['data'])) {
        return FALSE;
      }
      video_recorder_thumbnail_delete($item['data']);
      break;

    case 'title':
      if (!brightcove_recorder_retitle_video($item['brightcove_id'], $item['data'])) {
        return FALSE;
      }
  }
  db_query("DELETE FROM {brightcove_recorder_queue} WHERE qid = '%s'", $item['qid']);
}

/**
 * Deletes a video from the Brightcove CDN.
 */
function brightcove_recorder_delete_video($id) {
  module_load_include('module', 'brightcove');

  try {
    $bc = brightcove_initialize();
    $id = $bc->delete('video', $id);
  } catch (Exception $error) {
    $vars = array('@id' => $id, '@error' => (string)$error);
    watchdog('brightcove', 'Deleting video ID:@id from Brightcove failed. Error: @error', $vars, WATCHDOG_ERROR);
    return FALSE;
  }
  return TRUE;
}

/**
 * Uploads a thumbnail and still image for a video
 */
function brightcove_recorder_upload_thumb($id, $video_hash) {
  $thumb = $_SERVER['DOCUMENT_ROOT'] . base_path() . video_recorder_thumbnail_path($video_hash);
  $meta = array(
    'type' => 'THUMBNAIL',
  );

  try {
    $bc = brightcove_initialize();
    $bc->createImage('video', $thumb, $meta, $id);
    $meta['type'] = 'VIDEO_STILL';
    $bc->createImage('video', $thumb, $meta, $id);
  } catch (Exception $error) {
    $vars = array('@thumb' => $thumb, '@id' => $id, '@error' => (string)$error);
    watchdog('brightcove', "Uploading thumbnail image '@thumb' to Brightcove for video ID:@id failed. Error: @error", $vars, WATCHDOG_ERROR);
    return FALSE;
  }
  return TRUE;
}

function brightcove_recorder_retitle_video($id, $title) {
  $meta = array(
    'id' => $id,
    'name' => $title,
  );

  try {
    $bc = brightcove_initialize();
    $id = $bc->update('video', $meta);
  } catch (Exception $error) {
    $vars = array('@id' => $id, '@title' => $title, '@error' => (string)$error);
    watchdog('brightcove', 'Retitling video ID:@id to "@title" in Brightcove failed. Error: @error', $vars, WATCHDOG_ERROR);
    return FALSE;
  }
  return TRUE; 
}

/**
 * Implements hook_video_recorder_defaults_alter().
 */
function brightcove_recorder_video_recorder_defaults_alter($options) {
  // Not actually used for anything in the real world, just used for validation of the API
}
