<?php

/**
 * The default RTMP URL for recording the video streams.
 */
define('VIDEO_RECORDER_DEFAULT_RTMP_URL', 'rtmp://localhost/dvr/');

/**
 * The default HTTP URL for fetching recorded video streams.
 */
define('VIDEO_RECORDER_DEFAULT_HTTP_URL', 'http://localhost:8134/live/dvr/');

/**
 * The default bandwidth limit when recording video.
 */
define('VIDEO_RECORDER_DEFAULT_CAMERA_BANDWIDTH', 0);

/**
 * The default compression quality when recording video.
 */
define('VIDEO_RECORDER_DEFAULT_CAMERA_COMPRESSION', 70);

/**
 * Frames per second (FPS) for uploaded videos
 */
define('VIDEO_RECORDER_DEFAULT_CAMERA_FPS', 30);

/**
 * The number of seconds between each keyframe for uploaded videos.
 */
define('VIDEO_RECORDER_DEFAULT_CAMERA_KEYFRAME', 2);

/**
 * The maximum length (in seconds) for uploaded videos.
 */
define('VIDEO_RECORDER_DEFAULT_CAMERA_LENGTH', 600);



/**
 * Implements hook_menu().
 */
function video_recorder_menu() {
  $items = array();
  $items['admin/settings/video_recorder'] = array(
    'title' => 'Video recorder',
    'description' => 'Set basic recording settings for video recorder.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('video_recorder_admin'),
    'access arguments' => array('administer video recorder settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'video_recorder.admin.inc',
  );

  $items['video_recorder/record/%'] = array(
    'title' => 'Record Video',
    'description' => 'Record a video using flash',
    'page callback' => 'video_recorder_recorder',
    'page arguments' => array(2),
    'access arguments' => array('record video'),
    'type' => MENU_CALLBACK,
  );

  $items['video_recorder/record/popup/%'] = array(
    'title' => 'Record Video Popup',
    'description' => 'Record a video using flash in a modal frame',
    'page callback' => 'video_recorder_recorder_modal',
    'page arguments' => array(3),
    'access arguments' => array('record video'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function video_recorder_perm() {
  return array('administer video recorder settings', 'record video');
}

/**
 * Records a video using flash.
 */
function video_recorder_recorder($video_id) {
  $base = drupal_get_path('module', 'video_recorder');
  drupal_add_js("{$base}/video_recorder.js");

  $options = array(
    'id'          => 'video-recorder',
    'rtmp_url'    => NULL,
    'bandwidth'   => NULL,
    'compression' => NULL,
    'fps'         => NULL,
    'kfs'         => NULL,
    'length'      => NULL,
  );

  return theme('video_recorder_recorder', $video_id, $options);
}

/**
 * Records a video using flash in a modal frame.
 */
function video_recorder_recorder_modal($video_id) {
  modalframe_child_js();
  return video_recorder_recorder($video_id);
}

/**
 * Fetch the HTTP playback URL for a video.
 */
function video_recorder_playback_http_url($video_id) {
  $http_url = variable_get('video_recorder_http_url', VIDEO_RECORDER_DEFAULT_HTTP_URL);
  $url = check_plain($http_url . $video_id . '.flv');
  return $url;
}

/**
 * Fetch the RTMP playback URL for a video.
 */
function video_recorder_playback_http_rtmp($video_id) {
  $rtmp_url = variable_get('video_recorder_rtmp_url', VIDEO_RECORDER_DEFAULT_RTMP_URL);
  $url = check_plain($rtmp_url . $video_id);
  return $url;
}

/**
 * Implements hook_theme().
 */
function video_recorder_theme($existing, $type, $theme, $path) {
  return array(
    'video_recorder_recorder' => array(
      'arguments' => array(
        'video_id'  => NULL,
        'options'   => array(
          'id'          => NULL,
          'rtmp_url'    => NULL,
          'bandwidth'   => NULL,
          'compression' => NULL,
          'fps'         => NULL,
          'kfs'         => NULL,
          'length'      => NULL,
        ),
      ),
    ),
  );
}

/**
 * Themes the video recorder widget.
 *
 * @param $video_id
 *   The unique identifier for the video to be recorded.
 *
 * @param $options
 *   An array of parameters that get sent to the Flash recorder.
 *    id           - The id for the HTML element for the recorder.
 *    rtmp_url     - The target URL for streaming the video recording to.
 *    bandwidth    - The maximum amount of bandwidth an uploaded video will consume.
 *    compression  - The minimum compression quality an uploaded video must maintain.
 *    fps          - The number of frames per second an uploaded video will have.
 *    kfs          - The number of seconds in between each keyframe.
 *    length       - The maximum length of an uploaded video, measured in seconds.
 *
 * @return
 *   HTML ready for the browser
 */
function theme_video_recorder_recorder($video_id, $options=array()) {
  global $base_path;

  if ($options['id'] === NULL) {
    $options['id'] = 'video-recorder';
  }
  if ($options['rtmp_url'] === NULL) {
    $options['rtmp_url'] = variable_get('video_recorder_rtmp_url', VIDEO_RECORDER_DEFAULT_RTMP_URL);
  }
  if ($options['bandwidth'] === NULL) {
    $options['bandwidth'] = variable_get('video_recorder_camera_bandwidth', VIDEO_RECORDER_DEFAULT_CAMERA_BANDWIDTH);
  }
  if ($options['compression'] === NULL) {
    $options['compression'] = variable_get('video_recorder_camera_compression', VIDEO_RECORDER_DEFAULT_CAMERA_COMPRESSION);
  }
  if ($options['fps'] === NULL) {
    $options['fps'] = variable_get('video_recorder_camera_fps', VIDEO_RECORDER_DEFAULT_CAMERA_FPS);
  }
  if ($options['kfs'] === NULL) {
    $options['kfs'] = variable_get('video_recorder_camera_keyframe', VIDEO_RECORDER_DEFAULT_CAMERA_KEYFRAME);
  }
  if ($options['length'] === NULL) {
    $options['length'] = variable_get('video_recorder_camera_length', VIDEO_RECORDER_DEFAULT_CAMERA_LENGTH);
  }

  $video_id     = check_plain($video_id);
  $id           = check_plain($options['id']);
  $rtmp_url     = check_plain($options['rtmp_url']);
  $bandwidth    = check_plain($options['bandwidth']);
  $compression  = check_plain($options['compression']);
  $fps          = (int) $options['fps'];
  $kfs          = (int) $options['kfs'];
  $length       = (int) $options['length'];

  // calculate number of frames between each keyframe based on current FPS
  $keyframe = $fps * $kfs;

  $recorder = $base_path . drupal_get_path('module', 'video_recorder') . '/recorder.swf';

  $save = t('Save');

  $content = <<<HTML
    <div id="{$id}-wrapper" class="video-recorder-wrapper">
      <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="{$id}" class="video-recorder" width="640" height="480"
        codebase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">
        <param name="movie" value="{$recorder}" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#ffffff" />
        <param name="allowScriptAccess" value="sameDomain" />
        <param name="FlashVars" value="server={$rtmp_url}&fileName={$video_id}&height=480&width=640&maxLength={$length}&bandwidth={$bandwidth}&compression={$compression}&fps={$fps}&keyframe={$keyframe}" />
        <embed src="{$recorder}" quality="high" bgcolor="#ffffff" width="640" height="480" name="recorder" align="middle" 
          play="true" loop="false" quality="high" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" 
          pluginspage="http://www.adobe.com/go/getflashplayer" 
          FlashVars="server={$rtmp_url}&fileName={$video_id}&height=480&width=640&maxLength={$length}&bandwidth={$bandwidth}&compression={$compression}&fps={$fps}&keyframe={$keyframe}">
        </embed>
      </object>
    </div>

    <div id="{$id}-save-wrapper" class="video-recorder-save-wrapper ahah-progress">
      <a href="#" id="{$id}-save-{$video_id}" class="video-recorder-save" rel="{$id}">{$save}</a>
      <span style="display:none;" class="throbber"></span>
    </div>
HTML;

  return $content;
}
